### ISSUE TITLE
[Service Category Management] - Edit Service Category

### ISSUE THREAD

**Issue by tuandungbrse** [caubengoaiquoc/admin-frontend#10]
![image](https://user-images.githubusercontent.com/65501047/90343610-611a6200-e03c-11ea-91b9-d2f93125f83d.png)

- "Thêm hạng mục dịch vụ" ---> "Sửa.............."

**Comment by tuandungbrse** [comment]
Updated: [Service Management] same issues

**Comment by caubengoaiquoc** [comment]
vl hóa ra là ghi sai tiêu đề , đme cứ tưởng là ấn thêm nó ra sửa
