### ISSUE TITLE
After login, cant get avatar, admin information

### ISSUE THREAD

**Issue by peanutnbt** [caubengoaiquoc/admin-frontend#12]
After login success, seem like not call api to get admin infor
Problem make me cant not logout.
Must to refresh to get admin infor, and can logout.

![image](https://user-images.githubusercontent.com/32488457/90382977-b9d41400-e0a9-11ea-99c5-b10ea4a60fa3.png)

**Comment by caubengoaiquoc** [comment]
problem lead to thay vi problem make nhe

**Comment by peanutnbt** [comment]
brilliant !!!

**Comment by caubengoaiquoc** [comment]
da sua test va push len
