### ISSUE TITLE
[Create Coordinator]: Fail to create Coordinator

### ISSUE THREAD

**Issue by tuandungbrse** [caubengoaiquoc/admin-frontend#14]
1. **Input Data**
![image](https://user-images.githubusercontent.com/65501047/91062543-0940b400-e657-11ea-9475-6e9a8d3d9656.png)
2. **Front-end inform message**
![image](https://user-images.githubusercontent.com/65501047/91062491-f8903e00-e656-11ea-8980-a85c82938750.png)
3. **Server Response**
![image](https://user-images.githubusercontent.com/65501047/91062611-1f4e7480-e657-11ea-8c95-4db29a3f46b3.png)

![image](https://user-images.githubusercontent.com/65501047/91062980-9552db80-e657-11ea-9244-29975834955b.png)

**Comment by tuandungbrse** [comment]
![image](https://user-images.githubusercontent.com/65501047/91063656-76087e00-e658-11ea-9351-86e740e33f90.png)

sửa thành tiếng việt

**Comment by tuandungbrse** [comment]
![image](https://user-images.githubusercontent.com/65501047/91064392-62a9e280-e659-11ea-869c-879457c87a60.png)

nhập các trường hợp lệ riêng mật khẩu = 8 kí tự spaces, front-end ko hiển thị tên lỗi

**Comment by tuandungbrse** [comment]
nhập email quá dài vd: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@gmail.com
- server lỗi 500
- front-end không hiển thị nội dung lỗi.

**Comment by tuandungbrse** [comment]
![image](https://user-images.githubusercontent.com/65501047/91065844-2a0b0880-e65b-11ea-96bf-86a88d5608b4.png)

form sửa chỉnh lại button = Sửa

**Comment by peanutnbt** [comment]
db address với email trước t để 30 ký tự, vừa đổi ko giới hạn

**Comment by caubengoaiquoc** [comment]
cái này được chưa !?

**Comment by peanutnbt** [comment]
ông prevent space ở frontend đc k

**Comment by caubengoaiquoc** [comment]
gửi ảnh mới biết chỗ nào chứ má

**Comment by peanutnbt** [comment]
dấu cách ở password

**Comment by caubengoaiquoc** [comment]
đố tìm được trang nào space ko tính ở password

**Comment by tuandungbrse** [comment]
........................ close dc chua

**Comment by peanutnbt** [comment]
ok
