### ISSUE TITLE
[Customer Management] Search and Paging

### ISSUE THREAD

**Issue by tuandungbrse** [caubengoaiquoc/admin-frontend#8]
![image](https://user-images.githubusercontent.com/65501047/90328198-d64a5080-dfc4-11ea-8d17-417d0b078d23.png)
- search result: **1** record.
- paging pages: **2** pages.

**Comment by caubengoaiquoc** [comment]
![image](https://user-images.githubusercontent.com/36817895/90467826-54cafd80-e13f-11ea-8f8b-272923a65468.png)
i dont see this bug bro , can u more specific ?

**Comment by caubengoaiquoc** [comment]
đã sửa và push lên
