### ISSUE TITLE
[Doctor Management] Edit Doctor

### ISSUE THREAD

**Issue by tuandungbrse** [caubengoaiquoc/admin-frontend#9]
![image](https://user-images.githubusercontent.com/65501047/90340617-b4cc8180-e023-11ea-9b94-bb0e811f58cb.png)

- back-end
![image](https://user-images.githubusercontent.com/65501047/90340628-cb72d880-e023-11ea-80e9-17e662f4047f.png)

Note: Enter new doctor name, server throws query error, spinner keep spinning!

**Comment by peanutnbt** [comment]
Tôi test không sao, khả năng là do token bị lỗi, hay id doctor gửi lên undefined

**Comment by peanutnbt** [comment]
@tuandungbrse
